---
RecipeFormatVersion: '2020-01-25'
ComponentName: '{COMPONENT_NAME}'
ComponentVersion: '{COMPONENT_VERSION}'
ComponentDescription: 'Data Process.'
ComponentPublisher: '{COMPONENT_AUTHOR}'
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.shareflow.DataProcess:mqttproxy:1:
          policyDescription: 'Allows access to publish/subscribe to topics.'
          operations:
            - 'aws.greengrass#PublishToIoTCore'
            - 'aws.greengrass#SubscribeToIoTCore'
          resources:
            - 'sensor/ESP32'
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: 's3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.shareflow.DataProcess.zip'
        Unarchive: ZIP
    Lifecycle:
      Install: 'python3 -m venv iot_venv && . iot_venv/bin/activate && python3 -m pip install -r {artifacts:decompressedPath}/com.shareflow.DataProcess/requirements.txt'
      Run:
        Script: 'chmod 666 /dev/ttyUSB0 && . iot_venv/bin/activate && python3 -u {artifacts:decompressedPath}/com.shareflow.DataProcess/main.py'
        RequiresPrivilege: 'true'
